CREATE SCHEMA EC4_CC1N;
USE EC4_CC1N;

CREATE TABLE IF NOT EXISTS ALUNOS(
ALUNOS_CPF VARCHAR(14) PRIMARY KEY,
ALUNOS_NOME VARCHAR(50) NOT NULL,
ALUNOS_DATA_NASC DATE NOT NULL,
ALUNOS_LOGRADOURO VARCHAR(50) NOT NULL,
ALUNOS_NUM_LOG INT,
ALUNOS_BAIRRO VARCHAR (40) NOT NULL,
ALUNOS_CIDADE VARCHAR(40) NOT NULL,
ALUNOS_ESTADO VARCHAR(30) NOT NULL,
ALUNOS_CEP VARCHAR(10) NOT NULL
);


CREATE TABLE IF NOT EXISTS MODALIDADES(
MOD_COD INT PRIMARY KEY,
MOD_NOME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
INS_MATRICULA INT PRIMARY KEY,
INS_NOME VARCHAR(50),
INS_CPF VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS AULAS(
AULAS_COD INT PRIMARY KEY,
AULAS_DATA DATE NOT NULL,
AULAS_HORA TIME NOT NULL,
AULAS_CAPACIDADE INT,
AULAS_INSTRUTOR INT,
CONSTRAINT AUL_INS FOREIGN KEY(AULAS_INSTRUTOR) REFERENCES INSTRUTORES(INS_MATRICULA)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_COD INT PRIMARY KEY,
PAG_DATA_VENC DATE NOT NULL,
PAG_DATA_PAGAMENTO DATE,
PAG_STATUS ENUM('PENDENTE', 'VENCIDO', 'PAGO'),
PAG_CLIENTE VARCHAR(14),
CONSTRAINT PAG_CLI FOREIGN KEY(PAG_CLIENTE) REFERENCES ALUNOS(ALUNOS_CPF)
);


#CRIANDO A ASSOCIATIVA ALUNOS X AULAS
CREATE TABLE IF NOT EXISTS ALUNOS_AULAS(
ALAU_ALUNOS_CPF VARCHAR(14),
ALAU_AULAS_COD INT,
PRIMARY KEY(ALAU_ALUNOS_CPF, ALAU_AULAS_COD),
CONSTRAINT ALAU_AL FOREIGN KEY(ALAU_ALUNOS_CPF) REFERENCES ALUNOS(ALUNOS_CPF),
CONSTRAINT ALAU_AU FOREIGN KEY(ALAU_AULAS_COD) REFERENCES AULAS(AULAS_COD)
);


#CRIANDO A TABELA PLANO DE TREINAMENTO
CREATE TABLE IF NOT EXISTS PL_TREINAMENTO(
PLTR_AL_CPF VARCHAR(14),
PLTR_INS_MATRICULA INT,
PLTR_DATA DATE,
PRIMARY KEY(PLTR_AL_CPF, PLTR_INS_MATRICULA, PLTR_DATA),
PLTR_REGISTRO TEXT,
PLTR_MODALIDADE INT,
CONSTRAINT PLTR_AL FOREIGN KEY (PLTR_AL_CPF) REFERENCES ALUNOS(ALUNOS_CPF),
CONSTRAINT PLTR_INS FOREIGN KEY(PLTR_INS_MATRICULA) REFERENCES INSTRUTORES(INS_MATRICULA),
CONSTRAINT PLTR_MOD FOREIGN KEY(PLTR_MODALIDADE) REFERENCES MODALIDADES(MOD_COD)
);


#ALTERAÇÕES NA TABELA ALUNOS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A IDADE DOS ALUNOS:
ALTER TABLE ALUNOS ADD IDADE INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A IDADE DOS ALUNOS:
ALTER TABLE ALUNOS CHANGE COLUMN IDADE ALUNOS_IDADE INT;
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA NOME PODERÁ RECEBER:
ALTER TABLE ALUNOS MODIFY COLUMN ALUNOS_NOME VARCHAR(45);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (IDADE)
ALTER TABLE ALUNOS DROP COLUMN ALUNOS_IDADE;

#ALTERAÇÕES NA TABELA MODALIDADES
#CRIANDO UMA NOVA COLUNA QUE ARMAZENARÁ A DESCRIÇÃO DE CADA MODALIDADE:
ALTER TABLE MODALIDADES ADD DESCRICAO VARCHAR(50);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A DESCRIÇÃO DAS MODALIDADES:
ALTER TABLE MODALIDADES CHANGE COLUMN DESCRICAO MOD_DESCRICAO VARCHAR(50);
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA DESCRIÇÃO PODERÁ RECEBER:
ALTER TABLE MODALIDADES MODIFY COLUMN MOD_DESCRICAO TEXT;
#REMOVENDO A ÚLTIMA COLUNA CRIADA (DESCRIÇÃO)
ALTER TABLE MODALIDADES DROP COLUMN MOD_DESCRICAO;

#ALTERAÇÕES NA TABELA INSTRUTORES
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A IDADE DOS INSTRUTORES:
ALTER TABLE INSTRUTORES ADD IDADE INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A IDADE DOS INSTRUTORES:
ALTER TABLE INSTRUTORES CHANGE COLUMN IDADE INS_IDADE INT;
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA NOME PODERÁ RECEBER:
ALTER TABLE INSTRUTORES MODIFY COLUMN INS_NOME VARCHAR(45);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (IDADE)
ALTER TABLE INSTRUTORES DROP COLUMN INS_IDADE;

#ALTERAÇÕES NA TABELA AULAS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR OS EQUIPAMENTOS QUE SERÃO UTILIZADOS
ALTER TABLE AULAS ADD EQUIPAMENTO VARCHAR(20);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ OS EQUIPAMENTOS UTILIZADOS:
ALTER TABLE AULAS CHANGE COLUMN EQUIPAMENTO AULAS_EQUIPAMENTO VARCHAR(20);
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA EQUIPAMENTOS PODERÁ RECEBER:
ALTER TABLE AULAS MODIFY COLUMN AULAS_EQUIPAMENTO VARCHAR(30);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (EQUIPAMENTOS)
ALTER TABLE AULAS DROP COLUMN AULAS_EQUIPAMENTO;

#ALTERAÇÕES NA TABELA PAGAMENTOS 
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A FORMA DE PAGAMENTO UTILIZADA
ALTER TABLE PAGAMENTOS ADD FORMA_PAG VARCHAR(20);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A FORMA DE PAGAMENTO UTILIZADA:
ALTER TABLE PAGAMENTOS CHANGE COLUMN FORMA_PAG PAG_FORMA_PAG VARCHAR(20);
#ALTERANDO O TIPO DE DADOS QUE A COLUNA FORMA DE PAGAMENTO IRÁ RECEBER:
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_FORMA_PAG ENUM('DEBITO', 'CREDITO');
#REMOVENDO A ÚLTIMA COLUNA CRIADA (FORMA DE PAGAMENTO)
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_FORMA_PAG;

#ALTERAÇÕES NA TABELA ALUNOS_AULAS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O VALOR DA AULA
ALTER TABLE ALUNOS_AULAS ADD VALOR DECIMAL(10,3);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O VALOR:
ALTER TABLE ALUNOS_AULAS CHANGE COLUMN VALOR ALAU_VALOR DECIMAL(10,3);
#ALTERANDO O TIPO DE DADOS QUE A COLUNA VALOR IRÁ RECEBER:
ALTER TABLE ALUNOS_AULAS MODIFY COLUMN ALAU_VALOR DECIMAL(10,2);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (FORMA DE PAGAMENTO)
ALTER TABLE ALUNOS_AULAS DROP COLUMN ALAU_VALOR;

#ALTERAÇÕES NA TABELA PL_TREINAMENTO
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O VALOR DA ELABORAÇÃO DO PLANO
ALTER TABLE PL_TREINAMENTO ADD VALOR DECIMAL(10,3);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O VALOR:
ALTER TABLE PL_TREINAMENTO CHANGE COLUMN VALOR PLTR_VALOR DECIMAL(10,3);
#ALTERANDO O TIPO DE DADOS QUE A COLUNA VALOR IRÁ RECEBER:
ALTER TABLE PL_TREINAMENTO MODIFY COLUMN PLTR_VALOR DECIMAL(10,2);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (FORMA DE PAGAMENTO)
ALTER TABLE PL_TREINAMENTO DROP COLUMN PLTR_VALOR;


#REMOVENDO A TABELA ALUNOS_AULAS
DROP TABLE ALUNOS_AULAS;
