CREATE SCHEMA EC2_CC1N;
USE EC2_CC1N;

#CRIANDO A TABELA DA ENTIDADE PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TELEFONE VARCHAR(13) NOT NULL,
PASS_ESTADO VARCHAR(50) NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_RUA VARCHAR(50) NOT NULL,
PASS_NUM_RUA INT,
PASS_EMAIL VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA DA ENTIDADE AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO INT PRIMARY KEY,
AERON_FABRICANTE VARCHAR(50) NOT NULL, 
AERON_CAPACIDADE INT NOT NULL,
AERON_AUTONOMIA INT NOT NULL,
AERON_ANO_FABR YEAR NOT NULL,
AERON_MODELO VARCHAR(50) NOT NULL
);


#CRIANDO A TABELA DA ENTIDADE AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_PAIS VARCHAR(50) NOT NULL,
AEROP_LATITUDE VARCHAR(10),
AEROP_LONGITUDE VARCHAR(10)
);

#CRIANDO A TABELA DA ENTIDADE FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATA_NASC DATE NOT NULL,
FUNC_ESTADO VARCHAR(30) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_BAIRRO VARCHAR(50) NOT NULL,
FUNC_RUA VARCHAR(50) NOT NULL,
FUNC_NUM_RUA INT,
FUNC_CPF VARCHAR(14),
FUNC_FUNCAO VARCHAR(30)
);


#CRIANDO A TABELA DA ENTIDADE VOOS, COM SUAS RESPECTIVAS CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM INT,
VOO_AEROP_DESTINO INT,
VOO_AERONAVE INT,
CONSTRAINT VOO_AEROP_ORIG FOREIGN KEY(VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT VOO_AEROP_DEST FOREIGN KEY(VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT VOO_AERO FOREIGN KEY(VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

#CRIANDO A TABELA DA ENTIDADE RESERVAS, COM SUAS RESPECTIVAS CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS RESERVAS(
RESERVA_COD INT PRIMARY KEY,
PASS_CPF VARCHAR(14) NOT NULL,
VOO_ID INT,
CONSTRAINT RESERVAS_PASS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT RESERVAS_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);


#CRIANDO A TABELA DA ENTIDADE ASSOCIATIVA OPERAÇÃO X VOOS, COM SUAS RESPECTIVAS CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS OPERACAO_VOO(
OPVOO_VOO_ID INT,
OPVOO_FUNC_ID INT,
PRIMARY KEY(OPVOO_VOO_ID, OPVOO_FUNC_ID),
CONSTRAINT OPVOO_VOO FOREIGN KEY(OPVOO_VOO_ID) REFERENCES VOOS(VOO_ID),
CONSTRAINT OPVOO_FUNC FOREIGN KEY(OPVOO_FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);
