CREATE SCHEMA EC5_CC1N;
USE EC5_CC1N;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLI_CPF VARCHAR(14) PRIMARY KEY,
CLI_NOME VARCHAR(50) NOT NULL,
CLI_DATA_NASC DATE NOT NULL,
CLI_LOGRADOURO VARCHAR(50) NOT NULL,
CLI_NUM_LOG INT NOT NULL,
CLI_BAIRRO VARCHAR(40) NOT NULL,
CLI_CIDADE VARCHAR(40) NOT NULL,
CLI_ESTADO VARCHAR(30) NOT NULL,
CLI_CEP VARCHAR(10) NOT NULL,
CLI_FIDELIDADE ENUM('ATIVO', 'INATIVO')
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_ID INT PRIMARY KEY,
CNPJ VARCHAR(18),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_ID INT PRIMARY KEY,
PROD_QTD INT NOT NULL,
PROD_PRECO_UNIT DECIMAL(10,2) NOT NULL,
PROD_FORNECEDOR INT,
CONSTRAINT PROD_FORN FOREIGN KEY(PROD_FORNECEDOR) REFERENCES FORNECEDORES(FORN_ID)
);

CREATE TABLE IF NOT EXISTS VENDAS(
VENDAS_ID INT PRIMARY KEY,
VENDAS_DATA DATETIME NOT NULL,
VENDAS_CLIENTES VARCHAR(14),
CONSTRAINT VENDAS_CLI FOREIGN KEY(VENDAS_CLIENTES) REFERENCES CLIENTES(CLI_CPF)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
PAG_FORMA ENUM('DEBITO', 'CREDITO'),
PAG_VENDAS INT,
CONSTRAINT PAG_VEND FOREIGN KEY(PAG_VENDAS) REFERENCES VENDAS(VENDAS_ID)
);

#ASSOCIATIVA ENTRE PRODUTOS E VENDAS
CREATE TABLE IF NOT EXISTS PROD_VENDA(
PRODVEND_PRODUTOS INT,
PRODVEND_VENDAS INT,
PRIMARY KEY(PRODVEND_PRODUTOS, PRODVEND_VENDAS),
CONSTRAINT PRODVEND_PROD FOREIGN KEY(PRODVEND_PRODUTOS) REFERENCES PRODUTOS(PROD_ID),
CONSTRAINT PRODVEND_VEND FOREIGN KEY(PRODVEND_VENDAS) REFERENCES VENDAS(VENDAS_ID)
);


#ALTERAÇÕES NA TABELA CLIENTES
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A IDADE DOS CLIENTES:
ALTER TABLE CLIENTES ADD IDADE INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A IDADE DOS CLIENTES:
ALTER TABLE CLIENTES CHANGE COLUMN IDADE CLI_IDADE INT;
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA NOME PODERÁ RECEBER:
ALTER TABLE CLIENTES MODIFY COLUMN CLI_NOME VARCHAR(45);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (IDADE)
ALTER TABLE CLIENTES DROP COLUMN CLI_IDADE;


#ALTERAÇÕES NA TABELA FORNECEDORES:
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O NOME DO PERFIL DO INSTAGRAM DOS FORNECEDORES:
ALTER TABLE FORNECEDORES ADD INSTAGRAM VARCHAR(40);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O INSTAGRAM DOS FORNECEDORES:
ALTER TABLE FORNECEDORES CHANGE COLUMN INSTAGRAM FORN_INSTAGRAM VARCHAR(40);
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA NOME PODERÁ RECEBER:
ALTER TABLE FORNECEDORES MODIFY COLUMN EMAIL VARCHAR(45);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (INSTAGRAM)
ALTER TABLE FORNECEDORES DROP COLUMN FORN_INSTAGRAM;


#ALTERAÇÕES NA TABELA PRODUTOS:
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A COR DOS PRODUTOS:
ALTER TABLE PRODUTOS ADD COR VARCHAR(40);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A COR DOS PRODUTOS:
ALTER TABLE PRODUTOS CHANGE COLUMN COR PROD_COR VARCHAR(40);
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA COR PODERÁ RECEBER:
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_COR VARCHAR(30);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (COR)
ALTER TABLE PRODUTOS DROP COLUMN PROD_COR;


#ALTERAÇÕES NA TABELA VENDAS:
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O STATUS DO PAGAMENTO:
ALTER TABLE VENDAS ADD STATUS_VENDAS ENUM('PAGO', 'PENDENTE');
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A O STATUS DO PAGAMENTO:
ALTER TABLE VENDAS CHANGE COLUMN STATUS_VENDAS VENDAS_STATUS ENUM('PAGO', 'PENDENTE');
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA COR PODERÁ RECEBER:
ALTER TABLE VENDAS MODIFY COLUMN VENDAS_STATUS ENUM('PAGO', 'EM ABERTO', 'VENCIDO');
#REMOVENDO A ÚLTIMA COLUNA CRIADA (VENDAS_STATUS)
ALTER TABLE VENDAS DROP COLUMN VENDAS_STATUS;


#ALTERAÇÕES NA TABELA PAGAMENTOS:
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A FORMA DE PAGAMENTO
ALTER TABLE PAGAMENTOS ADD PAGAMENTO_FORMA ENUM('DEBITO', 'BOLETO', 'CREDITO');
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A FORMA DO PAGAMENTO:
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAGAMENTO_FORMA PAG_FORMA ENUM('DEBITO', 'BOLETO', 'CREDITO');
#ALTERANDO AS OPÇÕES QUE A COLUNA PAG_FORMA PODERÁ ASSUMIR:
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_FORMA ENUM('DEBITO', 'BOLETO', 'CREDITO', 'PIX');
#REMOVENDO A ÚLTIMA COLUNA CRIADA (PAG_FORMA)
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_FORMA;

#ALTERAÇÕES NA TABELA PROD_VENDA:
#CRIANDO UMA NOVA COLUNA PARA AMAZENAR O VALOR DO PRODUTO:
ALTER TABLE PROD_VENDA ADD VALOR INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O VALOR DO PRODUTO
ALTER TABLE PROD_VENDA CHANGE COLUMN VALOR PRODVEND_VALOR INT;
#ALTERANDO O TIPO DE DADO QUE A COLUNA QUE VAI RECEBER O VALOR DOS PRODUTOS
ALTER TABLE PROD_VENDA MODIFY COLUMN PRODVEND_VALOR DECIMAL(10,2);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (VALOR DOS PRODUTOS)
ALTER TABLE PROD_VENDA DROP COLUMN PRODVEND_VALOR;


#UTILIZANDO O COMANDO DROP PARA EXCLUIR A TABELA PROD_VENDA
DROP TABLE PROD_VENDA;
