CREATE SCHEMA EC5_CC1N;
USE EC5_CC1N;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLI_CPF VARCHAR(14) PRIMARY KEY,
CLI_NOME VARCHAR(50) NOT NULL,
CLI_DATA_NASC DATE NOT NULL,
CLI_LOGRADOURO VARCHAR(50) NOT NULL,
CLI_NUM_LOG INT NOT NULL,
CLI_BAIRRO VARCHAR(40) NOT NULL,
CLI_CIDADE VARCHAR(40) NOT NULL,
CLI_ESTADO VARCHAR(30) NOT NULL,
CLI_CEP VARCHAR(10) NOT NULL,
CLI_FIDELIDADE ENUM('ATIVO', 'INATIVO')
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_ID INT PRIMARY KEY,
CNPJ VARCHAR(18),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_ID INT PRIMARY KEY,
PROD_QTD INT NOT NULL,
PROD_PRECO_UNIT DECIMAL(10,2) NOT NULL,
PROD_FORNECEDOR INT,
CONSTRAINT PROD_FORN FOREIGN KEY(PROD_FORNECEDOR) REFERENCES FORNECEDORES(FORN_ID)
);

CREATE TABLE IF NOT EXISTS VENDAS(
VENDAS_ID INT PRIMARY KEY,
VENDAS_DATA DATETIME NOT NULL,
VENDAS_CLIENTES VARCHAR(14),
CONSTRAINT VENDAS_CLI FOREIGN KEY(VENDAS_CLIENTES) REFERENCES CLIENTES(CLI_CPF)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_ID INT PRIMARY KEY,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
PAG_FORMA ENUM('DEBITO', 'CREDITO'),
PAG_VENDAS INT,
CONSTRAINT PAG_VEND FOREIGN KEY(PAG_VENDAS) REFERENCES VENDAS(VENDAS_ID)
);

#ASSOCIATIVA ENTRE PRODUTOS E VENDAS
CREATE TABLE IF NOT EXISTS PROD_VENDA(
PRODVEND_PRODUTOS INT,
PRODVEND_VENDAS INT,
PRIMARY KEY(PRODVEND_PRODUTOS, PRODVEND_VENDAS),
CONSTRAINT PRODVEND_PROD FOREIGN KEY(PRODVEND_PRODUTOS) REFERENCES PRODUTOS(PROD_ID),
CONSTRAINT PRODVEND_VEND FOREIGN KEY(PRODVEND_VENDAS) REFERENCES VENDAS(VENDAS_ID)
);
