CREATE SCHEMA EC2_CC1N;
USE EC2_CC1N;

#CRIANDO A TABELA DA ENTIDADE PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TELEFONE VARCHAR(13) NOT NULL,
PASS_ESTADO VARCHAR(50) NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_RUA VARCHAR(50) NOT NULL,
PASS_NUM_RUA INT,
PASS_EMAIL VARCHAR(50) NOT NULL
);

#CRIANDO A TABELA DA ENTIDADE AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO INT PRIMARY KEY,
AERON_FABRICANTE VARCHAR(50) NOT NULL, 
AERON_CAPACIDADE INT NOT NULL,
AERON_AUTONOMIA INT NOT NULL,
AERON_ANO_FABR YEAR NOT NULL,
AERON_MODELO VARCHAR(50) NOT NULL
);


#CRIANDO A TABELA DA ENTIDADE AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_PAIS VARCHAR(50) NOT NULL,
AEROP_LATITUDE VARCHAR(10),
AEROP_LONGITUDE VARCHAR(10)
);

#CRIANDO A TABELA DA ENTIDADE FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATA_NASC DATE NOT NULL,
FUNC_ESTADO VARCHAR(30) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_BAIRRO VARCHAR(50) NOT NULL,
FUNC_RUA VARCHAR(50) NOT NULL,
FUNC_NUM_RUA INT,
FUNC_CPF VARCHAR(14),
FUNC_FUNCAO VARCHAR(30)
);


#CRIANDO A TABELA DA ENTIDADE VOOS, COM SUAS RESPECTIVAS CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM INT,
VOO_AEROP_DESTINO INT,
VOO_AERONAVE INT,
CONSTRAINT VOO_AEROP_ORIG FOREIGN KEY(VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT VOO_AEROP_DEST FOREIGN KEY(VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT VOO_AERO FOREIGN KEY(VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

#CRIANDO A TABELA DA ENTIDADE RESERVAS, COM SUAS RESPECTIVAS CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS RESERVAS(
RESERVA_COD INT PRIMARY KEY,
PASS_CPF VARCHAR(14) NOT NULL,
VOO_ID INT,
CONSTRAINT RESERVAS_PASS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT RESERVAS_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);


#CRIANDO A TABELA DA ENTIDADE ASSOCIATIVA RESULTANTE DA RELAÇÃO ENTRE AS ENTIDADES FUNCIONÁRIOS X VOOS, COM SUAS RESPECTIVAS CHAVES ESTRANGEIRAS
CREATE TABLE IF NOT EXISTS OPERACAO_VOO(
OPVOO_VOO_ID INT,
OPVOO_FUNC_ID INT,
PRIMARY KEY(OPVOO_VOO_ID, OPVOO_FUNC_ID),
CONSTRAINT OPVOO_VOO FOREIGN KEY(OPVOO_VOO_ID) REFERENCES VOOS(VOO_ID),
CONSTRAINT OPVOO_FUNC FOREIGN KEY(OPVOO_FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

#ALTERAÇÕES NA TABELA PASSAGEIROS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A IDADE DO PASSAGEIRO
ALTER TABLE PASSAGEIROS ADD IDADE INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A IDADE DO PASSAGEIRO
ALTER TABLE PASSAGEIROS CHANGE COLUMN IDADE PASS_IDADE INT;
#ALTERANDO A QUANTIDADE DE CARACTERES QUE A COLUNA BAIRRO PODERÁ RECEBER
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_BAIRRO VARCHAR(45);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (IDADE)
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_IDADE;


#ALTERAÇÕES NA TABELA AERONAVES
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O PESO DA AERONAVE
ALTER TABLE AERONAVES ADD PESO INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O PESO DA AERONAVE
ALTER TABLE AERONAVES CHANGE COLUMN PESO AERON_PESO INT;
#ALTERANDO O TIPO DE DADOS QUE O PESO DA AERONAVE ARMAZENARÁ
ALTER TABLE AERONAVES MODIFY COLUMN AERON_PESO DECIMAL(10,3);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (AERON_PESO)
ALTER TABLE AERONAVES DROP COLUMN AERON_PESO;


#ALTERAÇÕES NA TABELA AEROPORTOS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A ÁREA DO AEROPORTO
ALTER TABLE AEROPORTOS ADD AREA INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A ÁREA DO AEROPORTO
ALTER TABLE AEROPORTOS CHANGE COLUMN AREA AEROP_AREA INT;
#ALTERANDO O TIPO DE DADOS QUE A COLUNA QUE VAI RECEBER O NOME DO AEROPORTO
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_NOME VARCHAR(55);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (AEROP_AREA)
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_AREA;


#ALTERAÇÕES NA TABELA FUNCIONARIOS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR A IDADE DOS FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD IDADE INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ A IDADE DO FUNCIONARIOS
ALTER TABLE FUNCIONARIOS CHANGE COLUMN IDADE FUNC_IDADE INT;
#ALTERANDO O TIPO DE DADOS QUE A COLUNA QUE VAI RECEBER O NOME DOS FUNCIONARIOS
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_NOME VARCHAR(55);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (IDADE DOS FUNCIONARIOS)
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_IDADE;


#ALTERAÇÕES NA TABELA VOOS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O VALOR DO VOO
ALTER TABLE VOOS ADD VALOR INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O VALOR DO VOO
ALTER TABLE VOOS CHANGE COLUMN VALOR VOO_VALOR INT;
#ALTERANDO O TIPO DE DADOS QUE A COLUNA QUE VAI RECEBER O VALOR DOS VOOS
ALTER TABLE VOOS MODIFY COLUMN VOO_VALOR DECIMAL(10,2);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (VALOR DOS VOOS)
ALTER TABLE VOOS DROP COLUMN VOO_VALOR;


#ALTERAÇÕES NA TABELA RESERVAS
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O VALOR DAS RESERVAS
ALTER TABLE RESERVAS ADD VALOR INT;
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O VALOR DAS RESERVAS
ALTER TABLE RESERVAS CHANGE COLUMN VALOR RESERVA_VALOR INT;
#ALTERANDO O TIPO DE DADO QUE A COLUNA QUE VAI RECEBER O VALOR DAS RESERVAS
ALTER TABLE RESERVAS MODIFY COLUMN RESERVA_VALOR DECIMAL(10,2);
#REMOVENDO A ÚLTIMA COLUNA CRIADA (VALOR DAS RESERVAS)
ALTER TABLE RESERVAS DROP COLUMN RESERVA_VALOR;


#ALTERAÇÕES NA TABELA OPERACAO_VOO
#CRIANDO UMA NOVA COLUNA PARA ARMAZENAR O MODELO DA AERONAVE
ALTER TABLE OPERACAO_VOO ADD AERONAVE VARCHAR(20);
#ALTERANDO O NOME DA COLUNA QUE ARMAZENARÁ O MODELO DA AERONAVE
ALTER TABLE OPERACAO_VOO CHANGE COLUMN AERONAVE OPVOO_AERONAVE VARCHAR(20);
#ALTERANDO O TIPO DE DADO QUE A COLUNA QUE VAI RECEBER O VALOR DAS RESERVAS
ALTER TABLE OPERACAO_VOO MODIFY COLUMN OPVOO_AERONAVE INT;
#REMOVENDO A ÚLTIMA COLUNA CRIADA (VALOR DAS RESERVAS)
ALTER TABLE OPERACAO_VOO DROP COLUMN OPVOO_AERONAVE;
