CREATE SCHEMA EC4_CC1N;
USE EC4_CC1N;

CREATE TABLE IF NOT EXISTS ALUNOS(
ALUNOS_CPF VARCHAR(14) PRIMARY KEY,
ALUNOS_NOME VARCHAR(50) NOT NULL,
ALUNOS_DATA_NASC DATE NOT NULL,
ALUNOS_LOGRADOURO VARCHAR(50) NOT NULL,
ALUNOS_NUM_LOG INT,
ALUNOS_BAIRRO VARCHAR (40) NOT NULL,
ALUNOS_CIDADE VARCHAR(40) NOT NULL,
ALUNOS_ESTADO VARCHAR(30) NOT NULL,
ALUNOS_CEP VARCHAR(10) NOT NULL
);


CREATE TABLE IF NOT EXISTS MODALIDADES(
MOD_COD INT PRIMARY KEY,
MOD_NOME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
INS_MATRICULA INT PRIMARY KEY,
INS_NOME VARCHAR(50),
INS_CPF VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS AULAS(
AULAS_COD INT PRIMARY KEY,
AULAS_CAPACIDADE INT,
AULAS_INSTRUTOR INT,
CONSTRAINT AUL_INS FOREIGN KEY(AULAS_INSTRUTOR) REFERENCES INSTRUTORES(INS_MATRICULA)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_COD INT PRIMARY KEY,
PAG_DATA_VENC DATE NOT NULL,
PAG_DATA_PAGAMENTO DATE,
PAG_STATUS ENUM('PENDENTE', 'VENCIDO', 'PAGO'),
PAG_CLIENTE VARCHAR(14),
CONSTRAINT PAG_CLI FOREIGN KEY(PAG_CLIENTE) REFERENCES ALUNOS(ALUNOS_CPF)
);


#CRIANDO A ASSOCIATIVA ALUNOS X AULAS
CREATE TABLE IF NOT EXISTS ALUNOS_AULAS(
ALAU_ALUNOS_CPF VARCHAR(14),
ALAU_AULAS_COD INT,
PRIMARY KEY(ALAU_ALUNOS_CPF, ALAU_AULAS_COD),
CONSTRAINT ALAU_AL FOREIGN KEY(ALAU_ALUNOS_CPF) REFERENCES ALUNOS(ALUNOS_CPF),
CONSTRAINT ALAU_AU FOREIGN KEY(ALAU_AULAS_COD) REFERENCES AULAS(AULAS_COD)
);


#CRIANDO A TABELA PLANO DE TREINAMENTO
CREATE TABLE IF NOT EXISTS PL_TREINAMENTO(
PLTR_AL_CPF VARCHAR(14),
PLTR_INS_MATRICULA INT,
PLTR_DATA DATE,
PRIMARY KEY(PLTR_AL_CPF, PLTR_INS_MATRICULA, PLTR_DATA),
PLTR_REGISTRO TEXT,
PLTR_MODALIDADE INT,
CONSTRAINT PLTR_AL FOREIGN KEY (PLTR_AL_CPF) REFERENCES ALUNOS(ALUNOS_CPF),
CONSTRAINT PLTR_INS FOREIGN KEY(PLTR_INS_MATRICULA) REFERENCES INSTRUTORES(INS_MATRICULA),
CONSTRAINT PLTR_MOD FOREIGN KEY(PLTR_MODALIDADE) REFERENCES MODALIDADES(MOD_COD)
);
